[package]
name = "mve_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mve = { path = "../mve"}
pollster = "0.3.0"
